### ISSUE TITLE
Get error when run test code

### ISSUE THREAD

**Issue by ting1996** [awslabs/bike-kem#1]
After building code, I try to run bike-test but I get Illegal instruction (core dumped).
I use:
- OS: Ubuntu 18.04.2
- gcc: 7.5.0

**Comment by drucker-nir** [comment]
Hi,

The default compilation mode when running on an Intel CPU assumes that the CPU has the AVX2 extension.

What CPU do you use? Does it has AVX2 enabled by the OS?

If not you can always provide the `PORTABLE=1` flag (that requires OpenSSL) or the `PORTABLE=1 PCLMULQDQ=1` (that requires OpenSSL and that the CPU will have the PCLMUL instructions available).

**Comment by ting1996** [comment]
Thank for the help, bike-test can run with the PORTABLE=1 flag
