### ISSUE TITLE
Specification Clarification

### ISSUE THREAD

**Issue by 37eex9** [awslabs/bike-kem#17]
Hello,
I just want to make sure which specification of BIKE is implemented in this repository. In commit f25437d it states, that the implementation is updated to the round four BIKE submission, but the change in the [README.md](https://github.com/awslabs/bike-kem/commit/f25437d5074476dcbc0f101cc9bfc3feca5b7829#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) confuses me.

The text which is displayed says `"BIKE_Spec_2022.10.10.1.pd" (Spec v.5.1)` (actually the 'f' in 'pdf' is missing) which is correct, but you link to the specification v5.0 `https://bikesuite.org/files/v5.0/BIKE_Spec.2022.10.04.1.pdf`, instead of specification v5.1, which would be at `https://bikesuite.org/files/v5.0/BIKE_Spec.2022.10.10.1.pdf`.

Just wanted to clarify this before working with your implementation.

Thanks in advance.

**Comment by dkostic** [comment]
Hi, thanks for opening the issue. You are right, that was a wrong link. Fixed it in https://github.com/awslabs/bike-kem/commit/92d6a18e40c275c023227826b38bce2da1fde0dd.
