### ISSUE TITLE
How to decrypt ciphertext to plaintext ?

### ISSUE THREAD

**Issue by ting1996** [awslabs/bike-kem#2]
Why I can't find any decrypt function ?

**Comment by Shay-Gueron** [comment]
BIKE is a KEM (not a PKE). 
The counterpart of “encapsultation” (encaps) is decapsultion (decaps). 
Perhaps it would be useful to look at the BIKE specification document posted on https://bikesuite.org/

Regards, Shay G

**Comment by ting1996** [comment]
So encaps provide shared key to receiver and decaps provide shared key to sender. Then they use shared key to encrypt and decrypt, right?

**Comment by Shay-Gueron** [comment]
As a protocol, a KEM ends up with a shared key that is agreed between the communicating parties. The subsequent use of the shared key, by the parties, is not in the scope of the KEM. 
A common use is that the parties would use the key to encrypt/decrypt and authenticate messages.
