### ISSUE TITLE
Which specification ?  

### ISSUE THREAD

**Issue by lperret** [awslabs/bike-kem#4]
It seems to me that this code follows spec v3.2 and not the latest version of BIKE v4.0 ?

**Comment by drucker-nir** [comment]
Hi and thanks for the question. 

The README states: 

> This package corresponds to the specification document "BIKE_Round_3.2020.05.03.1.pdf

This corresponds to the count Ver 4.0. 
Do you see any mismatch? (if so, please provide exact details).
